### ISSUE TITLE
Nach Drag und drop kein history Eintrag 

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/slice_columns#11]
Aktuell ent steht kein Historyeintrag wenn per Drag und drop die slices verschoben werden.

**Comment by AndiLeni** [comment]
Die EP die da gebraucht werden scheinen die hier zu sein:
https://github.com/redaxo/redaxo/blob/main/redaxo/src/addons/structure/plugins/history/boot.php#L92

Soweit ich das sehe, müsste man einen der passenden EP manuell feuern und das History-Plugin sollte dann einen Snapshot erstellen.

**Comment by skerbis** [comment]
ich glaube es reicht ohne EP :-) , aber es ist die richtige Stelle :-) https://github.com/redaxo/redaxo/blob/19382c5ed4785b221548f4e793b9d8a722b4fd13/redaxo/src/addons/structure/plugins/history/boot.php#L112

**Comment by AndiLeni** [comment]
Ups, ja. makeSnapshot() is public.

**Comment by skerbis** [comment]
habs noch um eine Prüfung ergänzt ob history installiert ist
