### ISSUE TITLE
Javascript Fehler nach Klick auf Buttons am Block

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/slice_columns#12]
1. AddOn installiert/aktiviert 
2. Einstellungen einmal gespeichert
3. Danach in einen Artikel und die Buttons geklickt und es passierte nichts

**Konsole meldet:**

```
[Error] TypeError: null is not an object (evaluating 'parent.getAttribute')
	smaller (columns_sortablejs.js:77)
[Error] TypeError: null is not an object (evaluating 'parent.getAttribute')
	wider (columns_sortablejs.js:114)
```

**Comment by skerbis** [comment]
Welcher Browser?

**Comment by tbaddade** [comment]
> Welcher Browser?

- Safari 15.0
- Safari Technology Preview Release 132 (Safari 15.4, WebKit 16613.1.1.5)

**Comment by skerbis** [comment]
hmm 🙁
Bei mir: Version 15.0 (16612.1.29.41.4, 16612)

**Comment by skerbis** [comment]
Hab mehrere Browser getestet . strange

**Comment by tbaddade** [comment]
Liegt scheinbar am Tags AddOn ... Habs deaktiviert und so klappt es auch im Safari.
