### ISSUE TITLE
Icons sind sehr unscharf

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/slice_columns#13]
<img width="320" alt="Bildschirmfoto 2021-09-30 um 18 03 58" src="https://user-images.githubusercontent.com/338267/135491009-a702c5e8-68ad-4778-80fe-fb8c4343057d.png">

Eventuell Fontawesome Icons nutzen?

**Ideen**
1. [Spalten Icon](https://fontawesome.com/v4.7/icon/columns) dazu das [Plus](https://fontawesome.com/v4.7/icon/plus) und [Minus](https://fontawesome.com/v4.7/icon/minus) Icon
2. Diese zwei Icons [Forward](https://fontawesome.com/v4.7/icon/step-forward)/[Backward](https://fontawesome.com/v4.7/icon/step-backward) nur in der Reihenfolge für Smaller/Wider ändern, das käme den jetzigen Icons näher

**zu 1.** 
<img width="354" alt="Bildschirmfoto 2021-09-30 um 18 16 44" src="https://user-images.githubusercontent.com/338267/135492904-dd2c12e7-c7e5-4b01-8642-5f1e933c4e25.png">

**zu 2.**
<img width="345" alt="Bildschirmfoto 2021-09-30 um 18 15 24" src="https://user-images.githubusercontent.com/338267/135492712-8d518c49-7f58-44c5-a2e9-7ff19c453bb5.png">

**Comment by skerbis** [comment]
1 gefällt mir

**Comment by olien** [comment]
👍

**Comment by iceman-fx** [comment]
2 fände ich besser, da logischer.
Bei 1 denke ich, ich können eine zus. Spalte anlegen (ADD) bzw. entfernen (DEL).

**Comment by skerbis** [comment]
<img width="359" alt="Bildschirmfoto 2021-10-02 um 12 37 30" src="https://user-images.githubusercontent.com/791247/135712759-f4e0e1ba-0945-4179-a62c-85e36eb05fc9.png">
Meine Variante sieht jetzt so aus

**Comment by skerbis** [comment]
Warum ist eigentlich der online/offline Button nicht gleich hoch?

**Comment by skerbis** [comment]
@olien @iceman-fx  @tbaddade  so besser? Ist im Repo. 
Ich habe die von @AndiLeni eingesetzten Bilder ersetzt durch FontAwesome Icons und diese um 45° rotiert sowie zum Text mittig ausgerichtet.
