### ISSUE TITLE
klassisch Blöcke verschieben ... Fehlermeldung 

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/slice_columns#15]
Liefert: Block kann nicht verschoben werden. 
Ich habe es mit einem Pjax reload versucht. Ist aber doof weil langsam. 
Tendiere dazu die Block verschieben Buttons auszublenden.

**Comment by tbaddade** [comment]
Ich kann hier die Slices verschieben.

**Comment by skerbis** [comment]
@tbaddade nach drag & drop oder ändern der Breiten über die klassischen moveup movedown buttons.
Werden verschoben, dennoch kommt die Meldung 

<img width="1011" alt="Bildschirmfoto 2021-09-30 um 22 22 58" src="https://user-images.githubusercontent.com/791247/135525104-9273d741-7dd3-443b-a0a9-60c71587bf64.png">

**Comment by tbaddade** [comment]
Über moveup movedown. Es kam auch die grüne Meldung. Dragdrop hatte ich nicht genutzt.

**Comment by iceman-fx** [comment]
"Tendiere dazu die Block verschieben Buttons auszublenden."

Würde ich nicht machen, da dann die Touchbedienung nicht mehr (korrekt) möglich ist.

**Comment by skerbis** [comment]
ok. Dann lassen wir das mal so und warten ob noch mehr Meldungen kommen. Bei mir passiert es zumindest beim 2. Block.
