### ISSUE TITLE
Ausgabe-Problem

### ISSUE THREAD

**Issue by abra100pro** [FriendsOfREDAXO/slice_columns#20]
Ich habe ein kurzes Video dazu gemacht - das geht glaub' ich wirklich am schnellsten zum erklären:
https://www.dropbox.com/t/ntNd32eobXzCjgDz

**Comment by skerbis** [comment]
Hi. 
Das AddOn liefert im Artikel "nur" die Columns. 
Im Template müsstest du eine row hinterlegen. 

Wir haben es deswegen so gemacht, damit es für weitere Frameworks passt. So kannst du mit dem Container weiter spielen und weitere CSS dran setzen. 
Alternativ startest du eine ROW über ein ausgeschlossenes Modul und beendest es am Ende wieder um so Wrapper zu bauen. 

z.B. so: 
```
<div class="container">
  <div class="row">  
REX_ARTICLE[]
    </div>
    </div>
```

@abra100pro wegen dem Problem mit der Versionierung bitte mal die beta 3 im Installer laden. 
Link in der Readme habe ich auch gefixt. 
Warum das YFORM-Modul sich nicht ändern lässt ist mir nicht klar. Kann ich auch nicht reproduzieren. Hast du es evtl. in den Einstellungen ausgeschlossen?

**Comment by skerbis** [comment]
@abra100pro wegen dem Problem mit der Versionierung bitte mal die beta 2 im Installer laden.

**Comment by abra100pro** [comment]
Danke für das Sample (row) - nun klappt's perfekt. Habe auch die neueste Version installiert. 
In [diesem Video](https://www.dropbox.com/t/oUSjXAQTHAPX4ckR) seht Ihr, was für ein Problem ich mit Yform noch habe.
Das Form-Modul ist nicht ausgeschlossen.

**Comment by skerbis** [comment]
Hmm. Hast du das Problen auch wenn du den Ausgabe Code entfernst im Modul? Ich nutze das Modul nicht. Ist da JavaScript drin?

**Comment by abra100pro** [comment]
Nein, macht aber auch Sinn - dann hat es ja bei der Ausgabe nicht mehr von YForm.

**Comment by skerbis** [comment]
Ok. Werde ich im Moment nicht schlau draus. Die Struktur des Slices scheint anders zu sein. Ich denke eher es ist ein YForm Problem.

**Comment by skerbis** [comment]
Du kannst Die behelfen indem du im Modul 

```php
echo $yform->getForm();
```

durch 

```php 
if(rex::isFrontend())
{
echo $yform->getForm();
}
```
ersetzt. Dann wird das Formular nur im Frontend angezeigt.

**Comment by skerbis** [comment]
Hier geht's weiter
