### ISSUE TITLE
Grosse Bitte: Select-Feld und Spalter-Nummern

### ISSUE THREAD

**Issue by abra100pro** [FriendsOfREDAXO/slice_columns#21]
Ich habe jetzt ganz viel mit den Slice columns rumgeturnt und finde sie klasse! Es gibt noch ein, zwei Schwierigkeiten, die ich für Büromenschen-Redakteure sehe, zu denen ich auch später mal noch mich melde.

Zwei Sachen sind mir aber ein grosses Anliegen: Um an den Layouts rumzuschrauben, sind die Kleiner-/Grösser-Buttons (weniger/mehr-Spalten) extrem schnell mühsam. Siebenmal hier klicken, vier mal dort, mit der Maus immer nachhüpfen, das finde ich IMHO suboptimal. Wie wäre ein einfaches Select-Feld mit der Spaltenzahl? Damit wäre auch der zweite Punkt gelöst: Man sähe immer die Spaltenanzahl pro Block - das fände ich sehr hilfreich. So eine Lösung ähnlich der hier bei GitHub oben rechts:
<img width="139" alt="image" src="https://user-images.githubusercontent.com/7532646/148856552-0b7fb549-61e1-485b-a38a-0dd8e1ea7bc9.png">

Bitte nicht falsch verstehen - ich find's super. Diese beiden Punkte haben mich einfach sehr bald schon sehr gestört.
Bei Fragen einfach fragen. ;-)

**Comment by skerbis** [comment]
Gerne PR einreichen.

**Comment by abra100pro** [comment]
PR = Pull request?

**Comment by skerbis** [comment]
Japp gerne

**Comment by abra100pro** [comment]
Aehm, falls Du mich damit meinst: ich habe keinen Plan von Pull requests, sorry. Und will da auch nicht reinfummeln. Habe mal ansatzweise versucht, herauszufinden, was das macht, aber ohne Erfolg.

**Comment by skerbis** [comment]
Du kannst die Anzahl der Spalten und Schritte ja selbst definieren. Ich habe mich z.B. auf 4 Spalten festgelegt. 
Das sind dann weniger Clicks. Meinst braucht man nicht 12 Spalten.
