### ISSUE TITLE
Kein resize wenn <form> in der Ausgabe von Slide

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/slice_columns#22]
Wenn im Modul ein <form> in der Ausgabe des Slices ist, kann dieses nicht verändert werden. 

https://github.com/FriendsOfREDAXO/slice_columns/issues/20

**Comment by skerbis** [comment]
Ist das evtl. der Grund? 
https://github.com/FriendsOfREDAXO/slice_columns/blob/c37199ce7940f73143f78ab23ade261b6f6bf05d/lib/columns.php#L56

**Comment by skerbis** [comment]
@abra100pro  bitte testen

**Comment by AndiLeni** [comment]
> Ist das evtl. der Grund?
> 
> https://github.com/FriendsOfREDAXO/slice_columns/blob/c37199ce7940f73143f78ab23ade261b6f6bf05d/lib/columns.php#L56

Ich glaube, das wurde aus blöcks übernommen. Da sollte man klären, ob es einen tieferen Grund gibt, weshalb kein `<form>` drin sein durfte.

**Comment by skerbis** [comment]
Es sollte vermieden werden dass geöffnete Slices resized werden. Das sollte mein Pr lösen
